### ISSUE TITLE
405 throws nil pointer exception

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/util-user-dataset-handler-server#16]
```
handler-biom    | time="2020-06-26 15:31:47.485285" level=info msg="Method not allowed" endpoint="/job/bWlcHotSJu3BEVMfk6E3g" method=GET request-id=CGoFcXWGR source=server status=405
handler-biom    | 2020/06/26 15:31:47 http: panic serving 127.0.0.1:53842: runtime error: invalid memory address or nil pointer dereference
handler-biom    | goroutine 13 [running]:
handler-biom    | net/http.(*conn).serve.func1(0xc00009e140)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:1772 +0x139
handler-biom    | panic(0x95c4c0, 0xe83680)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/runtime/panic.go:975 +0x3e3
handler-biom    | github.com/gorilla/mux.(*Route).GetPathTemplate(...)
handler-biom    |       /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/route.go:629
handler-biom    | github.com/VEuPathDB/util-exporter-server/internal/server/middle.recordTime(0xbfb5a318dcebc50d, 0x18573314e95, 0xe95320, 0xac7640, 0xc0000a8680, 0x195)
handler-biom    |       /home/travis/gopath/src/github.com/VEuPathDB/util-user-dataset-handler-server/internal/server/middle/metrics.go:46 +0xc4
handler-biom    | github.com/VEuPathDB/util-exporter-server/internal/server/middle.MetricAgg.func1(0xabf960, 0xc0000b41c0, 0xc0000ac800)
handler-biom    |       /home/travis/gopath/src/github.com/VEuPathDB/util-user-dataset-handler-server/internal/server/middle/metrics.go:39 +0x10d
handler-biom    | net/http.HandlerFunc.ServeHTTP(0xc000306aa0, 0xabf960, 0xc0000b41c0, 0xc0000ac800)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:2012 +0x44
handler-biom    | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003740c0, 0xabf960, 0xc0000b41c0, 0xc0000ac600)
handler-biom    |       /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
handler-biom    | net/http.(*ServeMux).ServeHTTP(0xe95220, 0xabf960, 0xc0000b41c0, 0xc0000ac600)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:2387 +0x1a5
handler-biom    | net/http.serverHandler.ServeHTTP(0xc00033a2a0, 0xabf960, 0xc0000b41c0, 0xc0000ac600)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:2807 +0xa3
handler-biom    | net/http.(*conn).serve(0xc00009e140, 0xac1160, 0xc0000a8580)
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:1895 +0x86c
handler-biom    | created by net/http.(*Server).Serve
handler-biom    |       /home/travis/.gimme/versions/go1.14.4.linux.amd64/src/net/http/server.go:2933 +0x35c
```

**Comment by Foxcapades** [comment]
Should be resolved in v0.6.2
